---
galaxy_info:
  author: Peter Hudec
  description: installation and configuration of the apache tomcat from tar.gz
  company: CNC, a.s.
  license: license BSD
  min_ansible_version: 1.4
  #
  # Below are all platforms currently available. Just uncomment
  # the ones that apply to your role. If you don't see your
  # platform on this list, let us know and we'll get it added!
  #
  platforms:
  - name: EL
    versions:
    - all
    - 5
    - 6
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all

  categories:
  - web
dependencies: []
