---
- name: "copy logrotate config"
  action: template src={{ item }} dest=/etc/logrotate.d/apache-tomcat mode=644 owner=root group=root
  first_available_file:
    - "logrotate.conf.j2"
    - "{{ tomcat_dir_prefix }}/logrotate.conf.j2"
  tags: [ tomcat, config ]

- name: "copy bin/setenv.sh"
  action: template src={{ item }} dest={{ tomcat_install_dir }}/{{ tomcat_list[tomcat_version]['dirname'] }}/bin/setenv.sh mode=0750 owner={{ tomcat_user }} group={{ tomcat_group }}
  first_available_file:
    - "{{ tomcat_dir_prefix }}/bin/setenv.sh.{{ inventory_hostname }}.j2"
    - "{{ tomcat_dir_prefix }}/bin/setenv.sh.{{ ansible_distribution }}.j2"
    - "{{ tomcat_dir_prefix }}/bin/setenv.sh.j2"
    - "bin/setenv.sh.{{ inventory_hostname }}.j2"
    - "bin/setenv.sh.{{ ansible_distribution }}.j2"
    - "bin/setenv.sh.j2"
  tags: [ tomcat, config ]

- name: "copy extra configs"
  action: template src={{ tomcat_dir_prefix }}/{{ item.src }} dest={{ tomcat_install_dir }}/{{ tomcat_list[tomcat_version]['dirname'] }}/{{ item.dest }} mode={{ item.mode }} owner={{ tomcat_user }} group={{ tomcat_group }}
  with_items: tomcat_extra_conf
  when: "item.state == 'enabled'"
  tags: [ tomcat, config ]

- name: "remove extra libs"
  action: file path={{ tomcat_install_dir }}/{{ tomcat_list[tomcat_version]['dirname'] }}/{{ item.dest }} state=absent
  with_items: tomcat_extra_conf
  when: "item.state != 'enabled'"
  tags: [ tomcat, config ]

- name: "create server.xml"
  action: template src={{ item }} dest={{ tomcat_install_dir }}/{{ tomcat_list[tomcat_version]['dirname'] }}/conf/server.xml mode=0750 owner={{ tomcat_user }} group={{ tomcat_group }}
  first_available_file:
    - "{{ tomcat_dir_prefix }}/conf/server_{{ tomcat_config_template }}.j2"
    - "conf/server_{{ tomcat_config_template }}.j2"
  tags: [ tomcat, config ]
