---
- name: copy init script
  action: template src={{ item }} dest=/etc/init.d/{{ tomcat_service }} mode=0755 owner=root group=root
  first_available_file:
    - "{{ tomcat_dir_prefix }}/init.sh.{{ inventory_hostname }}.j2"
    - "{{ tomcat_dir_prefix }}/init.sh.{{ ansible_distribution }}.j2"
    - "{{ tomcat_dir_prefix }}/init.sh.j2"
    - "init.sh.{{ inventory_hostname }}.j2"
    - "init.sh.{{ ansible_distribution }}.j2"
    - "init.sh.j2"
  tags: [ tomcat, service ]

- name: ensure tomcat service started/stopped
  action: service name={{ tomcat_service }} state={{ tomcat_service_state }} enabled={{ tomcat_service_enabled }} pattern=org.apache.catalina.startup.Bootstrap
  tags: [ tomcat, service ]
